AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  SimpleExchangeRateServerlessApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.vkhoma.aws.handler.LambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  ServerlessExchangeRateApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/api/v1/rate/uahToCzk'
    Export:
      Name: ServerlessExchangeRateApi